version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: granja
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "1234:5432"
    restart: always
volumes:
  postgres_data:
    driver: local
