-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Duck"
(
    id uuid NOT NULL,
    name text NOT NULL,
    children uuid[],
    price double precision NOT NULL,
    mother_id uuid,
    sex "char",
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public." Customer"
(
    id uuid NOT NULL,
    name text NOT NULL,
    eligible_discount boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Sale"
(
    id uuid NOT NULL,
    sales_date timestamp without time zone NOT NULL,
    total_value double precision NOT NULL,
    costumer_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Duck_Sale"
(
    id uuid NOT NULL,
    sale_id uuid NOT NULL,
    duck_id uuid NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Duck"
    ADD FOREIGN KEY (mother_id)
    REFERENCES public."Duck" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sale"
    ADD FOREIGN KEY (costumer_id)
    REFERENCES public." Customer" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Duck_Sale"
    ADD FOREIGN KEY (sale_id)
    REFERENCES public."Sale" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Duck_Sale"
    ADD FOREIGN KEY (duck_id)
    REFERENCES public."Duck" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;